// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Demo
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Bond : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Bond\",\"namespace\":\"Demo\",\"fields\":[{\"name\":\"bondname\",\"t" +
				"ype\":\"string\"},{\"name\":\"price\",\"type\":\"int\"},{\"name\":\"timestamp\",\"type\":{\"type\":" +
				"\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
		private string _bondname;
		private int _price;
		private System.DateTime _timestamp;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Bond._SCHEMA;
			}
		}
		public string bondname
		{
			get
			{
				return this._bondname;
			}
			set
			{
				this._bondname = value;
			}
		}
		public int price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		public System.DateTime timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.bondname;
			case 1: return this.price;
			case 2: return this.timestamp;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.bondname = (System.String)fieldValue; break;
			case 1: this.price = (System.Int32)fieldValue; break;
			case 2: this.timestamp = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
