// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Demo
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class BondTrend : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"BondTrend\",\"namespace\":\"Demo\",\"fields\":[{\"name\":\"overall" +
				"change\",\"type\":\"double\"},{\"name\":\"lastminutechange\",\"type\":\"double\"},{\"name\":\"la" +
				"sthourchange\",\"type\":\"double\"}]}");
		private double _overallchange;
		private double _lastminutechange;
		private double _lasthourchange;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return BondTrend._SCHEMA;
			}
		}
		public double overallchange
		{
			get
			{
				return this._overallchange;
			}
			set
			{
				this._overallchange = value;
			}
		}
		public double lastminutechange
		{
			get
			{
				return this._lastminutechange;
			}
			set
			{
				this._lastminutechange = value;
			}
		}
		public double lasthourchange
		{
			get
			{
				return this._lasthourchange;
			}
			set
			{
				this._lasthourchange = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.overallchange;
			case 1: return this.lastminutechange;
			case 2: return this.lasthourchange;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.overallchange = (System.Double)fieldValue; break;
			case 1: this.lastminutechange = (System.Double)fieldValue; break;
			case 2: this.lasthourchange = (System.Double)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
