// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Demo
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class BondChange : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""BondChange"",""namespace"":""Demo"",""fields"":[{""name"":""overallchange"",""type"":""double""},{""name"":""lastminutechange"",""type"":""double""},{""name"":""lasthourchange"",""type"":""double""},{""name"":""BondEntries"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Bond"",""namespace"":""Demo"",""fields"":[{""name"":""bondname"",""type"":""string""},{""name"":""price"",""type"":""int""},{""name"":""timestamp"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}}}]}");
		private double _overallchange;
		private double _lastminutechange;
		private double _lasthourchange;
		private IList<Demo.Bond> _BondEntries;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return BondChange._SCHEMA;
			}
		}
		public double overallchange
		{
			get
			{
				return this._overallchange;
			}
			set
			{
				this._overallchange = value;
			}
		}
		public double lastminutechange
		{
			get
			{
				return this._lastminutechange;
			}
			set
			{
				this._lastminutechange = value;
			}
		}
		public double lasthourchange
		{
			get
			{
				return this._lasthourchange;
			}
			set
			{
				this._lasthourchange = value;
			}
		}
		public IList<Demo.Bond> BondEntries
		{
			get
			{
				return this._BondEntries;
			}
			set
			{
				this._BondEntries = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.overallchange;
			case 1: return this.lastminutechange;
			case 2: return this.lasthourchange;
			case 3: return this.BondEntries;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.overallchange = (System.Double)fieldValue; break;
			case 1: this.lastminutechange = (System.Double)fieldValue; break;
			case 2: this.lasthourchange = (System.Double)fieldValue; break;
			case 3: this.BondEntries = (IList<Demo.Bond>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
